from app.db.session import engine
from app.db.base import Base
from app.models import (
    agent,
    agent_relation,
    agent_run,
    agent_run_step,
    agent_performance,
    agent_template,
    admin_setting,
    audit_log,
    approval,
    employee,
    reminder,
    team,
    team_agent,
    task,
    telegram_bot,
    telegram_link,
    telegram_message,
    summary_schedule,
    model_performance,
    tool_credential,
    tool_performance,
    tool_registry,
    tool_request,
    usage_log,
    user,
    user_limit,
    user_performance,
    user_profile,
)


def init_db() -> None:
    _ = (
        agent,
        agent_relation,
        agent_run,
        agent_run_step,
        agent_performance,
        agent_template,
        admin_setting,
        audit_log,
        approval,
        employee,
        reminder,
        team,
        team_agent,
        task,
        telegram_bot,
        telegram_link,
        telegram_message,
        summary_schedule,
        model_performance,
        tool_credential,
        tool_performance,
        tool_registry,
        tool_request,
        usage_log,
        user,
        user_limit,
        user_performance,
        user_profile,
    )
    Base.metadata.create_all(bind=engine)
